[package]
name = "tweetnaclrs"
version = "0.1.0"
authors = ["David Johnston <dwtj@iastate.edu>",
           "Nik Kinkel <nskinkel@iastate.edu>"]
links = "tweetnacl"
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
lazy_static = "*"
libc = "*"
rand = "*"
